//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES공정별수량
    {
        public string 관리번호 { get; set; }
        public string 제품번호 { get; set; }
        public Nullable<int> 절단지시수량 { get; set; }
        public Nullable<int> 벤딩지시수량 { get; set; }
        public Nullable<int> 드릴지시수량 { get; set; }
        public Nullable<int> 용접지시수량 { get; set; }
        public Nullable<int> 절단불량수량 { get; set; }
        public Nullable<int> 벤딩불량수량 { get; set; }
        public Nullable<int> 드릴불량수량 { get; set; }
        public Nullable<int> 용접불량수량 { get; set; }
        public Nullable<System.DateTime> 실적시간 { get; set; }
    }
}
